### ISSUE TITLE
Add option to specify height

### ISSUE THREAD

**Issue by Gilfaro** [bpwhelan/GameSentenceMiner#42]
Add option to specify height or width or both. Currently only width is supported.

**Comment by bpwhelan** [comment]
The reason i went with this was just demand, I didn't want to expose this option as plain ffmpeg options since it's not as simple as `width 512` or something like that.

This will be
If both specified, use both.
if only one is specified, the other will be auto-scaled

should be fairly simple.

**Comment by bpwhelan** [comment]
height option added, closing
