### ISSUE TITLE
Support for avif

### ISSUE THREAD

**Issue by Gilfaro** [bpwhelan/GameSentenceMiner#43]
Currently options provided to ffmpeg are only for webp and even if you change extension for avif you cannot control quality.
`-c:v libaom-av1 -still-picture 1 -crf screenshot_quality` is the minimum amount of parameters where crf can be from 0 to 63, higher numbers indicating lower quality.

**Comment by bpwhelan** [comment]
Had not heard of avif until now. Will probably just add an override option that will replace these.

```python
ffmpeg_command = ffmpeg_base_command_list + [
        "-sseof", "-1",  # Seek to 1 second before the end of the video
        "-i", video_file,
        "-vframes", "1",  # Extract only one frame
        "-compression_level", "6", <--
        "-q:v", screenshot_quality, <--
    ]
```

**Comment by bpwhelan** [comment]
Custom settings added, closing.
